server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ocp?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: szx123
    # 连接池
    hikari:
      pool-name: DateHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲最大存活时间
      idle-timeout: 180000
      # 从连接池返回的连接自动提交
      auto-commit: true
      # 最大连接数
      maximum-pool-size: 10
      # 连接最大存活时间
      connection-timeout: 30000
      # 测试连接是否可用
      connection-test-query: select 1

# mybaits-plus

mybatis-plus:
  # mapper映射地址
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # Mybatis数据返回类型
  type-aliases-package: com.szx.server.pojo
  configuration:
    # 关闭自动驼峰命名
    map-underscore-to-camel-case: false


# mybatis sql 打印 方法接口所在的包, 不是mapper.xml所在包
logging:
  level:
    com.szx.server.mapper: debug

jwt:
  # jwt请求头
  tokenHeader: Authorization
  # 对应的密钥
  secret: ocp-secret
  # 有效时间
  expiration: 604800
  # JWT 负载中的开头
  tokenHead: Bearer